version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
      - image: localstack/localstack
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: create sns topic
          command: |
            aws sns create-topic --name TestTopic --endpoint-url http://localhost:4575
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m pytest tests/ -v
            mypy --ignore-missing-imports --check-untyped-defs ./src/

      - store_artifacts:
          path: test-reports
          destination: test-reports
